# Generated by Django 5.2.6 on 2025-09-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='ContohL Indomie Goreng', max_length=200)),
                ('tempat_produksi', models.CharField(help_text='Contoh: Pt Indofood', max_length=200)),
                ('halal', models.BooleanField(default=False, help_text='Centang jika barang ini bersertifikat halal')),
                ('tanggal_kadaluarsa', models.DateField(help_text='Pilih tanggal kadaluarsa Barang')),
                ('stok', models.IntegerField(help_text='Masukkan jumlah stok barang')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('pekerja', 'Pekerja'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
